# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reggae_cdmx', '0003_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reggae_cdmx.Venue'),
        ),
    ]
