language: python
python:
  - 3.5
  - 3.6
# Install dependencies
install: "pip install -r requirements/testing.txt"
# Run tests
script:
  - pytest --cov
  - pytest functional_tests
after_success:
  - coveralls
