language: python
cache: pip
python:
- 3.6
addons:
  ssh_known_hosts: ssh.pythonanywhere.com
before_install:
  - openssl aes-256-cbc -K $encrypted_7ec8dadd4ab6_key -iv $encrypted_7ec8dadd4ab6_iv -in .travis/deploy_key.enc -out deploy_key -d
install: pip install -r requirements/testing.txt
script:
- echo "{}" > secrets.json
# - pytest -k sys
- pytest -k unit -x --cov -n auto
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_key
  - ssh-add deploy_key
  - git remote add pythonanywhere flowfx@ssh.pythonanywhere.com:/home/flowfx/bare-repos/reggae-cdmx.git
  - git push -f pythonanywhere master
  - python .travis/reload-webapp.py
after_deploy:
  - coveralls
notifications:
  email: false
