language: python
python:
  - 3.6
# Install dependencies
install: "pip install -r requirements/testing.txt"
# Run tests
script:
  - pytest -k sys -x
  - pytest -k unit -x --cov -n auto
after_success:
  - coveralls
notifications:
  email: false
