# Generated by Django 2.0.2 on 2018-02-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='fb_page_url',
            field=models.URLField(blank=True, verbose_name='URL of the corresponding Facebook page'),
        ),
    ]
