# Generated by Django 2.0.2 on 2018-02-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_fb_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
