# Generated by Django 2.0.2 on 2018-02-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venue_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='fb_page_url',
        ),
        migrations.AddField(
            model_name='venue',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, max_length=1024, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
    ]
