# Generated by Django 2.0.1 on 2018-01-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20171211_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='facebook_event_url',
            new_name='fb_event_url',
        ),
    ]
