# Generated by Django 2.0.2 on 2018-02-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180106_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flyer_image',
            field=models.ImageField(blank=True, upload_to='event_flyers', verbose_name="image file of the event's promotion flyer"),
        ),
    ]
