# Generated by Django 2.0.2 on 2018-02-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180208_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='i-am-a-pole', max_length=255),
            preserve_default=False,
        ),
    ]
