# Generated by Django 2.0.2 on 2018-03-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20180305_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='fb_event_url',
            new_name='url',
        ),
    ]
